# -*- coding: utf-8 -*-
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
from MiuzPaths.cfg import version


APP = ['Project/start.py']
DATA_FILES = []
OPTIONS = {
    'iconfile':'Project/icon.icns',
    'plist': {
        'CFBundleName': 'MiuzPaths',
        'CFBundleShortVersionString':version, 
        'CFBundleVersion': version, 
        'CFBundleIdentifier': 'com.evlosh.MiuzPaths', 
        'NSHumanReadableCopyright': 'Created by Evgeny Loshkarev\nCopyright © 2022 MIUZ Diamonds. All rights reserved.'
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
